<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Surah; // تأكد أن الموديل موجود بالمسار الصحيح

class SurahSeeder extends Seeder
{
    public function run()
    {
        $surahs = [
            ['name' => 'الفاتحة', 'ayahs_count' => 7],
            ['name' => 'البقرة', 'ayahs_count' => 286],
            ['name' => 'آل عمران', 'ayahs_count' => 200],
            ['name' => 'النساء', 'ayahs_count' => 176],
            ['name' => 'المائدة', 'ayahs_count' => 120],
            ['name' => 'الأنعام', 'ayahs_count' => 165],
            ['name' => 'الأعراف', 'ayahs_count' => 206],
            ['name' => 'الأنفال', 'ayahs_count' => 75],
            ['name' => 'التوبة', 'ayahs_count' => 129],
            ['name' => 'يونس', 'ayahs_count' => 109],
            ['name' => 'هود', 'ayahs_count' => 123],
            ['name' => 'يوسف', 'ayahs_count' => 111],
            ['name' => 'الرعد', 'ayahs_count' => 43],
            ['name' => 'إبراهيم', 'ayahs_count' => 52],
            ['name' => 'الحجر', 'ayahs_count' => 99],
            ['name' => 'النحل', 'ayahs_count' => 128],
            ['name' => 'الإسراء', 'ayahs_count' => 111],
            ['name' => 'الكهف', 'ayahs_count' => 110],
            ['name' => 'مريم', 'ayahs_count' => 98],
            ['name' => 'طه', 'ayahs_count' => 135],
            ['name' => 'الأنبياء', 'ayahs_count' => 112],
            ['name' => 'الحج', 'ayahs_count' => 78],
            ['name' => 'المؤمنون', 'ayahs_count' => 118],
            ['name' => 'النور', 'ayahs_count' => 64],
            ['name' => 'الفرقان', 'ayahs_count' => 77],
            ['name' => 'الشعراء', 'ayahs_count' => 227],
            ['name' => 'النمل', 'ayahs_count' => 93],
            ['name' => 'القصص', 'ayahs_count' => 88],
            ['name' => 'العنكبوت', 'ayahs_count' => 69],
            ['name' => 'الروم', 'ayahs_count' => 60],
            ['name' => 'لقمان', 'ayahs_count' => 34],
            ['name' => 'السجدة', 'ayahs_count' => 30],
            ['name' => 'الأحزاب', 'ayahs_count' => 73],
            ['name' => 'سبأ', 'ayahs_count' => 54],
            ['name' => 'فاطر', 'ayahs_count' => 45],
            ['name' => 'يس', 'ayahs_count' => 83],
            ['name' => 'الصافات', 'ayahs_count' => 182],
            ['name' => 'ص', 'ayahs_count' => 88],
            ['name' => 'الزمر', 'ayahs_count' => 75],
            ['name' => 'غافر', 'ayahs_count' => 85],
            ['name' => 'فصلت', 'ayahs_count' => 54],
            ['name' => 'الشورى', 'ayahs_count' => 53],
            ['name' => 'الزخرف', 'ayahs_count' => 89],
            ['name' => 'الدخان', 'ayahs_count' => 59],
            ['name' => 'الجاثية', 'ayahs_count' => 37],
            ['name' => 'الأحقاف', 'ayahs_count' => 35],
            ['name' => 'محمد', 'ayahs_count' => 38],
            ['name' => 'الفتح', 'ayahs_count' => 29],
            ['name' => 'الحجرات', 'ayahs_count' => 18],
            ['name' => 'ق', 'ayahs_count' => 45],
            ['name' => 'الذاريات', 'ayahs_count' => 60],
            ['name' => 'الطور', 'ayahs_count' => 49],
            ['name' => 'النجم', 'ayahs_count' => 62],
            ['name' => 'القمر', 'ayahs_count' => 55],
            ['name' => 'الرحمن', 'ayahs_count' => 78],
            ['name' => 'الواقعة', 'ayahs_count' => 96],
            ['name' => 'الحديد', 'ayahs_count' => 29],
            ['name' => 'المجادلة', 'ayahs_count' => 22],
            ['name' => 'الحشر', 'ayahs_count' => 24],
            ['name' => 'الممتحنة', 'ayahs_count' => 13],
            ['name' => 'الصف', 'ayahs_count' => 14],
            ['name' => 'الجمعة', 'ayahs_count' => 11],
            ['name' => 'المنافقون', 'ayahs_count' => 11],
            ['name' => 'التغابن', 'ayahs_count' => 18],
            ['name' => 'الطلاق', 'ayahs_count' => 12],
            ['name' => 'التحريم', 'ayahs_count' => 12],
            ['name' => 'الملك', 'ayahs_count' => 30],
            ['name' => 'القلم', 'ayahs_count' => 52],
            ['name' => 'الحاقة', 'ayahs_count' => 52],
            ['name' => 'المعارج', 'ayahs_count' => 44],
            ['name' => 'نوح', 'ayahs_count' => 28],
            ['name' => 'الجن', 'ayahs_count' => 28],
            ['name' => 'المزمل', 'ayahs_count' => 20],
            ['name' => 'المدثر', 'ayahs_count' => 56],
            ['name' => 'القيامة', 'ayahs_count' => 40],
            ['name' => 'الإنسان', 'ayahs_count' => 31],
            ['name' => 'المرسلات', 'ayahs_count' => 50],
            ['name' => 'النبأ', 'ayahs_count' => 40],
            ['name' => 'النازعات', 'ayahs_count' => 46],
            ['name' => 'عبس', 'ayahs_count' => 42],
            ['name' => 'التكوير', 'ayahs_count' => 29],
            ['name' => 'الانفطار', 'ayahs_count' => 19],
            ['name' => 'المطففين', 'ayahs_count' => 36],
            ['name' => 'الانشقاق', 'ayahs_count' => 25],
            ['name' => 'البروج', 'ayahs_count' => 22],
            ['name' => 'الطارق', 'ayahs_count' => 17],
            ['name' => 'الأعلى', 'ayahs_count' => 19],
            ['name' => 'الغاشية', 'ayahs_count' => 26],
            ['name' => 'الفجر', 'ayahs_count' => 30],
            ['name' => 'البلد', 'ayahs_count' => 20],
            ['name' => 'الشمس', 'ayahs_count' => 15],
            ['name' => 'الليل', 'ayahs_count' => 21],
            ['name' => 'الضحى', 'ayahs_count' => 11],
            ['name' => 'الشرح', 'ayahs_count' => 8],
            ['name' => 'التين', 'ayahs_count' => 8],
            ['name' => 'العلق', 'ayahs_count' => 19],
            ['name' => 'القدر', 'ayahs_count' => 5],
            ['name' => 'البينة', 'ayahs_count' => 8],
            ['name' => 'الزلزلة', 'ayahs_count' => 8],
            ['name' => 'العاديات', 'ayahs_count' => 11],
            ['name' => 'القارعة', 'ayahs_count' => 11],
            ['name' => 'التكاثر', 'ayahs_count' => 8],
            ['name' => 'العصر', 'ayahs_count' => 3],
            ['name' => 'الهمزة', 'ayahs_count' => 9],
            ['name' => 'الفيل', 'ayahs_count' => 5],
            ['name' => 'قريش', 'ayahs_count' => 4],
            ['name' => 'الماعون', 'ayahs_count' => 7],
            ['name' => 'الكوثر', 'ayahs_count' => 3],
            ['name' => 'الكافرون', 'ayahs_count' => 6],
            ['name' => 'النصر', 'ayahs_count' => 3],
            ['name' => 'المسد', 'ayahs_count' => 5],
            ['name' => 'الإخلاص', 'ayahs_count' => 4],
            ['name' => 'الفلق', 'ayahs_count' => 5],
            ['name' => 'الناس', 'ayahs_count' => 6],
        ];

        foreach ($surahs as $surah) {
            Surah::create($surah);
        }
        // Surah::insert($surahs);
    }
}
